use rusqlite::{params, Connection};
use uuid::Uuid;

use crate::error::{CoreError, Result};
use crate::models::project::{
    CreateProjectInput, ListProjectsOptions, Project, UpdateProjectInput,
};

/// Create a new project. Timestamps are generated by DB DEFAULT.
pub fn create(conn: &Connection, input: CreateProjectInput) -> Result<Project> {
    let name = input.name.trim().to_string();
    if name.is_empty() {
        return Err(CoreError::Validation("name cannot be empty".into()));
    }

    let id = Uuid::new_v4().to_string();

    conn.execute(
        "INSERT INTO project (id, name, description, style_prompt, global_seed)
         VALUES (?1, ?2, ?3, ?4, ?5)",
        params![
            id,
            name,
            input.description.unwrap_or_default(),
            input.style_prompt.unwrap_or_default(),
            input.global_seed,
        ],
    )?;

    get_by_id(conn, &id)
}

/// Get a project by ID.
pub fn get_by_id(conn: &Connection, id: &str) -> Result<Project> {
    conn.query_row(
        "SELECT id, name, description, style_prompt, global_seed, created_at, updated_at
         FROM project WHERE id = ?1",
        params![id],
        |row| {
            Ok(Project {
                id: row.get(0)?,
                name: row.get(1)?,
                description: row.get(2)?,
                style_prompt: row.get(3)?,
                global_seed: row.get(4)?,
                created_at: row.get(5)?,
                updated_at: row.get(6)?,
            })
        },
    )
    .map_err(|e| match e {
        rusqlite::Error::QueryReturnedNoRows => CoreError::NotFound {
            entity: "project",
            id: id.to_string(),
        },
        other => CoreError::Sqlite(other),
    })
}

/// List projects ordered by created_at DESC with pagination.
pub fn list(conn: &Connection, opts: ListProjectsOptions) -> Result<Vec<Project>> {
    let limit = opts.limit.unwrap_or(50).clamp(1, 200);
    let offset = opts.offset.unwrap_or(0).max(0);

    let mut stmt = conn.prepare(
        "SELECT id, name, description, style_prompt, global_seed, created_at, updated_at
         FROM project ORDER BY created_at DESC LIMIT ?1 OFFSET ?2",
    )?;

    let projects = stmt
        .query_map(params![limit, offset], |row| {
            Ok(Project {
                id: row.get(0)?,
                name: row.get(1)?,
                description: row.get(2)?,
                style_prompt: row.get(3)?,
                global_seed: row.get(4)?,
                created_at: row.get(5)?,
                updated_at: row.get(6)?,
            })
        })?
        .collect::<std::result::Result<Vec<_>, _>>()?;

    Ok(projects)
}

/// Update a project. Only fields that are `Some` will be modified.
pub fn update(conn: &Connection, id: &str, input: UpdateProjectInput) -> Result<Project> {
    let _ = get_by_id(conn, id)?;

    if let Some(ref name) = input.name
        && name.trim().is_empty()
    {
        return Err(CoreError::Validation("name cannot be empty".into()));
    }

    let mut sets: Vec<String> = vec!["updated_at = datetime('now')".to_string()];
    let mut params: Vec<Box<dyn rusqlite::types::ToSql>> = vec![];
    let mut idx = 1u32;

    if let Some(ref name) = input.name {
        sets.push(format!("name = ?{idx}"));
        params.push(Box::new(name.trim().to_string()));
        idx += 1;
    }
    if let Some(ref desc) = input.description {
        sets.push(format!("description = ?{idx}"));
        params.push(Box::new(desc.clone()));
        idx += 1;
    }
    if let Some(ref sp) = input.style_prompt {
        sets.push(format!("style_prompt = ?{idx}"));
        params.push(Box::new(sp.clone()));
        idx += 1;
    }
    if let Some(ref maybe_seed) = input.global_seed {
        sets.push(format!("global_seed = ?{idx}"));
        params.push(Box::new(*maybe_seed));
        idx += 1;
    }

    let sql = format!(
        "UPDATE project SET {} WHERE id = ?{idx}",
        sets.join(", ")
    );
    params.push(Box::new(id.to_string()));

    let param_refs: Vec<&dyn rusqlite::types::ToSql> = params.iter().map(|p| p.as_ref()).collect();
    conn.execute(&sql, param_refs.as_slice())?;

    get_by_id(conn, id)
}

/// Delete a project by ID.
pub fn delete(conn: &Connection, id: &str) -> Result<()> {
    let affected = conn.execute("DELETE FROM project WHERE id = ?1", params![id])?;
    if affected == 0 {
        return Err(CoreError::NotFound {
            entity: "project",
            id: id.to_string(),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::open_sync;
    use std::path::Path;

    fn setup() -> Connection {
        open_sync(Path::new(":memory:")).unwrap()
    }

    #[test]
    fn test_create_project() {
        let conn = setup();
        let project = create(
            &conn,
            CreateProjectInput {
                name: "测试项目".into(),
                description: Some("描述".into()),
                style_prompt: None,
                global_seed: None,
            },
        )
        .unwrap();

        assert!(!project.id.is_empty());
        assert_eq!(project.name, "测试项目");
        assert_eq!(project.description, "描述");
        assert!(!project.created_at.is_empty());
        assert_eq!(project.created_at, project.updated_at);
    }

    #[test]
    fn test_create_project_empty_name_fails() {
        let conn = setup();
        let result = create(
            &conn,
            CreateProjectInput {
                name: "  ".into(),
                description: None,
                style_prompt: None,
                global_seed: None,
            },
        );
        assert!(matches!(result, Err(CoreError::Validation(_))));
    }

    #[test]
    fn test_get_by_id_not_found() {
        let conn = setup();
        let result = get_by_id(&conn, "nonexistent");
        assert!(matches!(result, Err(CoreError::NotFound { .. })));
    }

    #[test]
    fn test_list_with_pagination() {
        let conn = setup();
        for i in 0..5 {
            create(
                &conn,
                CreateProjectInput {
                    name: format!("Project {i}"),
                    description: None,
                    style_prompt: None,
                    global_seed: None,
                },
            )
            .unwrap();
        }

        let page1 = list(
            &conn,
            ListProjectsOptions {
                limit: Some(2),
                offset: Some(0),
            },
        )
        .unwrap();
        assert_eq!(page1.len(), 2);

        let page2 = list(
            &conn,
            ListProjectsOptions {
                limit: Some(2),
                offset: Some(2),
            },
        )
        .unwrap();
        assert_eq!(page2.len(), 2);

        let all = list(&conn, ListProjectsOptions::default()).unwrap();
        assert_eq!(all.len(), 5);
    }

    #[test]
    fn test_update_project_partial() {
        let conn = setup();
        let project = create(
            &conn,
            CreateProjectInput {
                name: "Original".into(),
                description: Some("desc".into()),
                style_prompt: None,
                global_seed: None,
            },
        )
        .unwrap();

        let updated = update(
            &conn,
            &project.id,
            UpdateProjectInput {
                name: Some("Renamed".into()),
                description: None,
                style_prompt: None,
                global_seed: None,
            },
        )
        .unwrap();

        assert_eq!(updated.name, "Renamed");
        assert_eq!(updated.description, "desc");
    }

    #[test]
    fn test_update_project_clear_global_seed() {
        let conn = setup();
        let project = create(
            &conn,
            CreateProjectInput {
                name: "With Seed".into(),
                description: None,
                style_prompt: None,
                global_seed: Some(42),
            },
        )
        .unwrap();
        assert_eq!(project.global_seed, Some(42));

        // Clear global_seed to NULL
        let updated = update(
            &conn,
            &project.id,
            UpdateProjectInput {
                name: None,
                description: None,
                style_prompt: None,
                global_seed: Some(None),
            },
        )
        .unwrap();
        assert_eq!(updated.global_seed, None);
    }

    #[test]
    fn test_update_project_empty_name_fails() {
        let conn = setup();
        let project = create(
            &conn,
            CreateProjectInput {
                name: "Test".into(),
                description: None,
                style_prompt: None,
                global_seed: None,
            },
        )
        .unwrap();

        let result = update(
            &conn,
            &project.id,
            UpdateProjectInput {
                name: Some("  ".into()),
                description: None,
                style_prompt: None,
                global_seed: None,
            },
        );
        assert!(matches!(result, Err(CoreError::Validation(_))));
    }

    #[test]
    fn test_delete_project() {
        let conn = setup();
        let project = create(
            &conn,
            CreateProjectInput {
                name: "To Delete".into(),
                description: None,
                style_prompt: None,
                global_seed: None,
            },
        )
        .unwrap();

        delete(&conn, &project.id).unwrap();
        assert!(matches!(
            get_by_id(&conn, &project.id),
            Err(CoreError::NotFound { .. })
        ));
    }

    #[test]
    fn test_delete_nonexistent_fails() {
        let conn = setup();
        let result = delete(&conn, "nonexistent");
        assert!(matches!(result, Err(CoreError::NotFound { .. })));
    }
}
