// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	createApiAccount: (input: CreateApiAccountInput_Deserialize) => typedError<ApiAccount_Serialize, IpcError_Serialize>(__TAURI_INVOKE("create_api_account", { input })),
	deleteApiAccount: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_api_account", { id })),
	getApiAccount: (id: string) => typedError<ApiAccount_Serialize, IpcError_Serialize>(__TAURI_INVOKE("get_api_account", { id })),
	listApiAccounts: (providerId: string | null) => typedError<ApiAccount_Serialize[], IpcError_Serialize>(__TAURI_INVOKE("list_api_accounts", { providerId })),
	updateApiAccount: (id: string, input: UpdateApiAccountInput_Deserialize) => typedError<ApiAccount_Serialize, IpcError_Serialize>(__TAURI_INVOKE("update_api_account", { id, input })),
	/**
	 *  Confirms that the keyring still holds a non-empty credential for this
	 *  account. NOT a network test — that arrives in MS2 under a different name
	 *  (`test_connection`) so the UI can offer both without collision.
	 */
	verifyApiAccountStorage: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("verify_api_account_storage", { id })),
	/**
	 *  Bind (or unbind) an asset to a shot. `Some(shot_id)` overwrites the prior
	 *  binding silently — UI surfaces (e.g. canvas drag-to-shot) are expected to
	 *  confirm overwrites themselves before calling. `None` clears the binding.
	 *  Returns the post-update row so the caller's cache can refresh in a single
	 *  roundtrip.
	 */
	assignAssetToShot: (id: string, shotId: string | null) => typedError<Asset, IpcError_Serialize>(__TAURI_INVOKE("assign_asset_to_shot", { id, shotId })),
	/**
	 *  Delete an asset row. Files on disk are intentionally not removed; a future
	 *  GC sweep (V2) reconciles orphaned files. See spec-12 §"错误场景".
	 */
	deleteAsset: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_asset", { id })),
	/**
	 *  Translate a project-root-relative `file_path` (as stored on rows like
	 *  `character.reference_image_path`) back to the canonical asset row. Returns
	 *  `Ok(None)` when no asset matches — callers decide how to surface that to
	 *  the user (e.g. "selected reference image is not in the asset library").
	 */
	findAssetByPath: (projectId: string, filePath: string) => typedError<{
	id: string,
	project_id: string,
	shot_id: string | null,
	asset_type: AssetType,
	original_name: string,
	/**
	 *  Stored relative to the project root (e.g. `assets/{id}.png`), always
	 *  `/`-separated for cross-platform stability.
	 */
	file_path: string,
	thumbnail_path: string | null,
	file_size: number,
	content_hash: string | null,
	metadata_json: string | null,
	source: AssetSource,
	/**  Free-form user classification tag. Empty string when unset. */
	label: string,
	created_at: string,
	updated_at: string,
} | null, IpcError_Serialize>(__TAURI_INVOKE("find_asset_by_path", { projectId, filePath })),
	getAsset: (id: string) => typedError<Asset, IpcError_Serialize>(__TAURI_INVOKE("get_asset", { id })),
	/**
	 *  Import an external image into the project.
	 * 
	 *  Runs in three stages so the file-IO stage (potentially tens of MiB of
	 *  copy + image decode) does NOT hold the tokio-rusqlite worker. Stages 1
	 *  and 3 are short DB-bound calls; stage 2 is `spawn_blocking` filesystem
	 *  work. See spec-12 §"导入流水线（三段式）" for the design rationale.
	 */
	importAsset: (input: ImportAssetInput) => typedError<Asset, IpcError_Serialize>(__TAURI_INVOKE("import_asset", { input })),
	/**
	 *  Return the distinct non-empty `label` values currently used across the
	 *  project's assets. The frontend asset library uses this to populate the
	 *  label filter dropdown; "all" and "unlabeled" options are added by the UI.
	 */
	listAssetLabels: (projectId: string) => typedError<string[], IpcError_Serialize>(__TAURI_INVOKE("list_asset_labels", { projectId })),
	listAssets: (opts: ListAssetsOptions) => typedError<Asset[], IpcError_Serialize>(__TAURI_INVOKE("list_assets", { opts })),
	/**
	 *  Update the free-form `label` of an asset (e.g. user-applied tag in the
	 *  asset library). An empty string clears the tag. Returns the post-update
	 *  row so the caller's cache can refresh in a single roundtrip.
	 */
	updateAssetLabel: (id: string, label: string) => typedError<Asset, IpcError_Serialize>(__TAURI_INVOKE("update_asset_label", { id, label })),
	/**
	 *  Update an asset's display name (`original_name`). Empty/whitespace-only
	 *  strings are rejected (`VALIDATION_ERROR`) — the UI should disable the
	 *  save button until the field has content. Returns the post-update row so
	 *  the caller's cache can refresh in a single roundtrip.
	 */
	updateAssetOriginalName: (id: string, originalName: string) => typedError<Asset, IpcError_Serialize>(__TAURI_INVOKE("update_asset_original_name", { id, originalName })),
	deleteCanvasLayout: (episodeId: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_canvas_layout", { episodeId })),
	getCanvasLayout: (episodeId: string) => typedError<{
	id: string,
	episode_id: string,
	nodes_json: string,
	edges_json: string,
	viewport_json: string,
	updated_at: string,
} | null, IpcError_Serialize>(__TAURI_INVOKE("get_canvas_layout", { episodeId })),
	upsertCanvasLayout: (input: UpsertCanvasLayoutInput) => typedError<CanvasLayout, IpcError_Serialize>(__TAURI_INVOKE("upsert_canvas_layout", { input })),
	createCharacter: (input: CreateCharacterInput) => typedError<Character, IpcError_Serialize>(__TAURI_INVOKE("create_character", { input })),
	/**
	 *  Delete a character. Schema `ON DELETE CASCADE` removes its costumes;
	 *  callers display the affected count by querying costumes first.
	 */
	deleteCharacter: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_character", { id })),
	getCharacter: (id: string) => typedError<Character, IpcError_Serialize>(__TAURI_INVOKE("get_character", { id })),
	listCharacters: (opts: ListCharactersOptions) => typedError<Character[], IpcError_Serialize>(__TAURI_INVOKE("list_characters", { opts })),
	updateCharacter: (id: string, input: UpdateCharacterInput_Deserialize) => typedError<Character, IpcError_Serialize>(__TAURI_INVOKE("update_character", { id, input })),
	checkCliInstalled: () => typedError<CliStatus, IpcError_Serialize>(__TAURI_INVOKE("check_cli_installed")),
	installCli: () => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("install_cli")),
	uninstallCli: () => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("uninstall_cli")),
	createCostume: (input: CreateCostumeInput) => typedError<Costume, IpcError_Serialize>(__TAURI_INVOKE("create_costume", { input })),
	deleteCostume: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_costume", { id })),
	getCostume: (id: string) => typedError<Costume, IpcError_Serialize>(__TAURI_INVOKE("get_costume", { id })),
	listCostumes: (opts: ListCostumesOptions) => typedError<Costume[], IpcError_Serialize>(__TAURI_INVOKE("list_costumes", { opts })),
	updateCostume: (id: string, input: UpdateCostumeInput_Deserialize) => typedError<Costume, IpcError_Serialize>(__TAURI_INVOKE("update_costume", { id, input })),
	/**
	 *  Open a native file picker filtered to common image extensions. Returns
	 *  `None` if the user cancelled. Mirrors `pick_project_directory` so the
	 *  frontend keeps a single picker pattern across the app.
	 */
	pickImageFile: () => typedError<string | null, IpcError_Serialize>(__TAURI_INVOKE("pick_image_file")),
	/**
	 *  Open a native directory picker. Returns `None` if the user cancelled.
	 * 
	 *  Implemented with the non-blocking callback variant + a oneshot channel so
	 *  the tokio executor thread is not parked while the user is choosing.
	 */
	pickProjectDirectory: () => typedError<string | null, IpcError_Serialize>(__TAURI_INVOKE("pick_project_directory")),
	createEpisode: (input: CreateEpisodeInput) => typedError<Episode, IpcError_Serialize>(__TAURI_INVOKE("create_episode", { input })),
	deleteEpisode: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_episode", { id })),
	getEpisode: (id: string) => typedError<Episode, IpcError_Serialize>(__TAURI_INVOKE("get_episode", { id })),
	listEpisodes: (opts: ListEpisodesOptions) => typedError<Episode[], IpcError_Serialize>(__TAURI_INVOKE("list_episodes", { opts })),
	reorderEpisodes: (projectId: string, orderedIds: string[]) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("reorder_episodes", { projectId, orderedIds })),
	updateEpisode: (id: string, input: UpdateEpisodeInput_Deserialize) => typedError<Episode, IpcError_Serialize>(__TAURI_INVOKE("update_episode", { id, input })),
	checkFfmpeg: () => typedError<FfmpegStatus, IpcError_Serialize>(__TAURI_INVOKE("check_ffmpeg")),
	concatVideos: (inputs: string[], output: string) => typedError<string, IpcError_Serialize>(__TAURI_INVOKE("concat_videos", { inputs, output })),
	extractThumbnail: (input: string, timestampMs: number, output: string) => typedError<string, IpcError_Serialize>(__TAURI_INVOKE("extract_thumbnail", { input, timestampMs, output })),
	extractThumbnailStrip: (input: string, intervalMs: number, thumbWidth: number) => typedError<ThumbnailStripResult, IpcError_Serialize>(__TAURI_INVOKE("extract_thumbnail_strip", { input, intervalMs, thumbWidth })),
	probeVideo: (path: string) => typedError<VideoMetadata, IpcError_Serialize>(__TAURI_INVOKE("probe_video", { path })),
	splitVideo: (input: string, splitPointsMs: number[], outputDir: string, mode: TrimMode) => typedError<string[], IpcError_Serialize>(__TAURI_INVOKE("split_video", { input, splitPointsMs, outputDir, mode })),
	trimVideo: (input: string, startMs: number, endMs: number, output: string, mode: TrimMode) => typedError<string, IpcError_Serialize>(__TAURI_INVOKE("trim_video", { input, startMs, endMs, output, mode })),
	createEpisodeCheckpoint: (input: CreateCheckpointInput) => typedError<EpisodeCheckpoint, IpcError_Serialize>(__TAURI_INVOKE("create_episode_checkpoint", { input })),
	deleteEpisodeCheckpoint: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_episode_checkpoint", { id })),
	listEpisodeCheckpoints: (episodeId: string) => typedError<EpisodeCheckpointListItem[], IpcError_Serialize>(__TAURI_INVOKE("list_episode_checkpoints", { episodeId })),
	restoreEpisodeCheckpoint: (checkpointId: string) => typedError<Episode, IpcError_Serialize>(__TAURI_INVOKE("restore_episode_checkpoint", { checkpointId })),
	createProject: (input: CreateProjectInput) => typedError<Project, IpcError_Serialize>(__TAURI_INVOKE("create_project", { input })),
	/**
	 *  Delete project metadata only. The on-disk root_path directory and its
	 *  contents are intentionally preserved; V2 will add an explicit purge flag.
	 */
	deleteProject: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_project", { id })),
	getProject: (id: string) => typedError<Project, IpcError_Serialize>(__TAURI_INVOKE("get_project", { id })),
	listProjects: (opts: {
	limit?: number | null,
	offset?: number | null,
} | null) => typedError<Project[], IpcError_Serialize>(__TAURI_INVOKE("list_projects", { opts })),
	updateProject: (id: string, input: UpdateProjectInput_Deserialize) => typedError<Project, IpcError_Serialize>(__TAURI_INVOKE("update_project", { id, input })),
	createProp: (input: CreatePropInput) => typedError<Prop, IpcError_Serialize>(__TAURI_INVOKE("create_prop", { input })),
	deleteProp: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_prop", { id })),
	getProp: (id: string) => typedError<Prop, IpcError_Serialize>(__TAURI_INVOKE("get_prop", { id })),
	listProps: (opts: ListPropsOptions) => typedError<Prop[], IpcError_Serialize>(__TAURI_INVOKE("list_props", { opts })),
	updateProp: (id: string, input: UpdatePropInput_Deserialize) => typedError<Prop, IpcError_Serialize>(__TAURI_INVOKE("update_prop", { id, input })),
	listModels: (providerId: string | null) => typedError<Model[], IpcError_Serialize>(__TAURI_INVOKE("list_models", { providerId })),
	listProviders: () => typedError<Provider[], IpcError_Serialize>(__TAURI_INVOKE("list_providers")),
	createScene: (input: CreateSceneInput) => typedError<Scene, IpcError_Serialize>(__TAURI_INVOKE("create_scene", { input })),
	deleteScene: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_scene", { id })),
	getScene: (id: string) => typedError<Scene, IpcError_Serialize>(__TAURI_INVOKE("get_scene", { id })),
	listScenes: (opts: ListScenesOptions) => typedError<Scene[], IpcError_Serialize>(__TAURI_INVOKE("list_scenes", { opts })),
	updateScene: (id: string, input: UpdateSceneInput_Deserialize) => typedError<Scene, IpcError_Serialize>(__TAURI_INVOKE("update_scene", { id, input })),
	adoptTaskResult: (shotId: string, taskId: string) => typedError<Shot, IpcError_Serialize>(__TAURI_INVOKE("adopt_task_result", { shotId, taskId })),
	createShot: (input: CreateShotInput) => typedError<Shot, IpcError_Serialize>(__TAURI_INVOKE("create_shot", { input })),
	deleteShot: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_shot", { id })),
	getShot: (id: string) => typedError<Shot, IpcError_Serialize>(__TAURI_INVOKE("get_shot", { id })),
	linkShotSubject: (shotId: string, subjectId: string, subjectKind: SubjectKind) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("link_shot_subject", { shotId, subjectId, subjectKind })),
	listShotLinks: (shotId: string) => typedError<ShotLinks, IpcError_Serialize>(__TAURI_INVOKE("list_shot_links", { shotId })),
	listShots: (opts: ListShotsOptions) => typedError<Shot[], IpcError_Serialize>(__TAURI_INVOKE("list_shots", { opts })),
	reorderShots: (episodeId: string, orderedIds: string[]) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("reorder_shots", { episodeId, orderedIds })),
	unadoptShot: (shotId: string) => typedError<Shot, IpcError_Serialize>(__TAURI_INVOKE("unadopt_shot", { shotId })),
	unlinkShotSubject: (shotId: string, subjectId: string, subjectKind: SubjectKind) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("unlink_shot_subject", { shotId, subjectId, subjectKind })),
	updateShot: (id: string, input: UpdateShotInput_Deserialize) => typedError<Shot, IpcError_Serialize>(__TAURI_INVOKE("update_shot", { id, input })),
	cancelTask: (taskId: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("cancel_task", { taskId })),
	getTask: (taskId: string) => typedError<GenerationTask, IpcError_Serialize>(__TAURI_INVOKE("get_task", { taskId })),
	getTaskMaxConcurrency: () => typedError<number, IpcError_Serialize>(__TAURI_INVOKE("get_task_max_concurrency")),
	listTaskEvents: (taskId: string) => typedError<GenerationTaskEvent[], IpcError_Serialize>(__TAURI_INVOKE("list_task_events", { taskId })),
	listTasks: (projectId: string | null, status: "pending" | "running" | "success" | "failed" | "cancelled" | null, shotId: string | null, limit: number | null) => typedError<GenerationTask[], IpcError_Serialize>(__TAURI_INVOKE("list_tasks", { projectId, status, shotId, limit })),
	setTaskMaxConcurrency: (value: number) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("set_task_max_concurrency", { value })),
	submitTask: (input: CreateGenerationTaskInput) => typedError<string, IpcError_Serialize>(__TAURI_INVOKE("submit_task", { input })),
	submitTasksBatch: (inputs: CreateGenerationTaskInput[]) => typedError<SubmitBatchOutcome, IpcError_Serialize>(__TAURI_INVOKE("submit_tasks_batch", { inputs })),
	createVideoClip: (input: CreateVideoClipInput) => typedError<VideoClip, IpcError_Serialize>(__TAURI_INVOKE("create_video_clip", { input })),
	deleteVideoClip: (id: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("delete_video_clip", { id })),
	exportVideoClips: (episodeId: string, outputPath: string) => typedError<string, IpcError_Serialize>(__TAURI_INVOKE("export_video_clips", { episodeId, outputPath })),
	listVideoClips: (episodeId: string) => typedError<VideoClip[], IpcError_Serialize>(__TAURI_INVOKE("list_video_clips", { episodeId })),
	reorderVideoClips: (ids: string[]) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("reorder_video_clips", { ids })),
	updateVideoClip: (id: string, input: UpdateVideoClipInput) => typedError<VideoClip, IpcError_Serialize>(__TAURI_INVOKE("update_video_clip", { id, input })),
	/**
	 *  Current workspace mount state. Drives the frontend's onboarding vs
	 *  main-app routing decision.
	 */
	getWorkspaceStatus: () => typedError<WorkspaceStatus, IpcError_Serialize>(__TAURI_INVOKE("get_workspace_status")),
	/**
	 *  Hot-mount a workspace at `path`: write the pointer config, open the DB,
	 *  register the asset-protocol scope, spawn the task engine, and install
	 *  `MountedState` into the OnceLock. After this returns the frontend can
	 *  `invalidate(['workspace', 'status'])` and the app slides into the main
	 *  UI — no process restart involved.
	 * 
	 *  Refuses if a workspace is already mounted (the OnceLock would reject
	 *  the `.set` anyway, but we want a clean error code for the frontend).
	 */
	mountWorkspace: (path: string) => typedError<WorkspaceStatus, IpcError_Serialize>(__TAURI_INVOKE("mount_workspace", { path })),
	/**
	 *  Probe a candidate workspace directory. Pure inspection — no writes, no
	 *  state mutation. The frontend calls this before showing a confirmation
	 *  dialog so the user sees the right message for what they're about to do.
	 */
	probeWorkspace: (path: string) => typedError<WorkspaceProbe, IpcError_Serialize>(__TAURI_INVOKE("probe_workspace", { path })),
	/**
	 *  Switch the workspace pointer and schedule a clean exit so the user
	 *  relaunches into the new workspace. Used when a workspace is already
	 *  mounted — hot-swap isn't feasible because the frontend's React Query
	 *  cache + router state would still reference projects under the old
	 *  workspace.
	 * 
	 *  Steps:
	 *  1. Probe + validate the target.
	 *  2. Materialise the new workspace on disk (`prepare_workspace` mkdir +
	 *     open + migrations) so `setup()` finds a ready `mango.db` on the
	 *     next boot. **This is the bit that was missing in the first cut and
	 *     caused the relaunch to fall back to onboarding** when the user
	 *     picked an empty directory.
	 *  3. Write the pointer config.
	 *  4. Schedule `app.exit(0)` 200 ms out so the IPC response delivers and
	 *     the frontend can render a "please relaunch" toast.
	 * 
	 *  We use `app.exit(0)` rather than `app.restart()` because under
	 *  `tauri dev` restart re-execs the cargo target binary and disconnects
	 *  from the cargo-tauri parent that owns the vite watcher (observed as
	 *  "click does nothing"). Exiting cleanly is reliable in both dev and
	 *  production.
	 */
	setWorkspaceAndRelaunch: (path: string) => typedError<null, IpcError_Serialize>(__TAURI_INVOKE("set_workspace_and_relaunch", { path })),
};

/** Events */
export const events = {
	episodeDataRestored: makeEvent<EpisodeDataRestored>("episode-data-restored"),
	ffmpegProgressTick: makeEvent<FfmpegProgressTick>("ffmpeg-progress-tick"),
	taskEventLogged: makeEvent<TaskEventLogged>("task-event-logged"),
	taskProgressTick: makeEvent<TaskProgressTick>("task-progress-tick"),
	taskStatusChanged: makeEvent<TaskStatusChanged>("task-status-changed"),
};

/* Types */
/**
 *  IPC-exposed account row. Crucially excludes `api_key_ref`: the frontend has
 *  no business reading the keyring entry name, and not exporting it makes
 *  accidental misuse a type error.
 */
export type ApiAccount = ApiAccount_Serialize | ApiAccount_Deserialize;

/**
 *  IPC-exposed account row. Crucially excludes `api_key_ref`: the frontend has
 *  no business reading the keyring entry name, and not exporting it makes
 *  accidental misuse a type error.
 */
export type ApiAccount_Deserialize = {
	id: string,
	provider_id: string,
	label: string,
	key_last4: string,
	/**
	 *  Public-side OSS configuration. Only populated for accounts with an
	 *  `oss` block in `params_json`. The access_key_secret never appears here
	 *  — it lives in the keyring under entry `api_account:<id>:oss_secret`.
	 */
	oss_config: OssConfigPublic_Deserialize | null,
	usage_quota: number | null,
	usage_used: number,
	last_used_at: string | null,
	created_at: string,
};

/**
 *  IPC-exposed account row. Crucially excludes `api_key_ref`: the frontend has
 *  no business reading the keyring entry name, and not exporting it makes
 *  accidental misuse a type error.
 */
export type ApiAccount_Serialize = {
	id: string,
	provider_id: string,
	label: string,
	key_last4: string,
	/**
	 *  Public-side OSS configuration. Only populated for accounts with an
	 *  `oss` block in `params_json`. The access_key_secret never appears here
	 *  — it lives in the keyring under entry `api_account:<id>:oss_secret`.
	 */
	oss_config?: OssConfigPublic_Serialize | null,
	usage_quota: number | null,
	usage_used: number,
	last_used_at: string | null,
	created_at: string,
};

export type Asset = {
	id: string,
	project_id: string,
	shot_id: string | null,
	asset_type: AssetType,
	original_name: string,
	/**
	 *  Stored relative to the project root (e.g. `assets/{id}.png`), always
	 *  `/`-separated for cross-platform stability.
	 */
	file_path: string,
	thumbnail_path: string | null,
	file_size: number,
	content_hash: string | null,
	metadata_json: string | null,
	source: AssetSource,
	/**  Free-form user classification tag. Empty string when unset. */
	label: string,
	created_at: string,
	updated_at: string,
};

/**
 *  Provenance of an asset row. `Imported` covers user drag-drop / file picker
 *  flows; `Generated` covers artifacts written back by the runner after a
 *  successful generation_task.
 */
export type AssetSource = "imported" | "generated";

export type AssetType = "image" | "video" | "audio" | "script";

/**
 *  Canvas layout for a single episode. `nodes_json` / `edges_json` /
 *  `viewport_json` are opaque JSON blobs owned by the frontend's React Flow
 *  state — core never parses their inner structure, only that they are
 *  well-formed JSON. See spec-21 for rationale.
 */
export type CanvasLayout = {
	id: string,
	episode_id: string,
	nodes_json: string,
	edges_json: string,
	viewport_json: string,
	updated_at: string,
};

export type Character = {
	id: string,
	project_id: string,
	name: string,
	description: string,
	appearance_prompt: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type CliStatus = {
	installed: boolean,
	symlink_target: string | null,
	points_to_current_app: boolean,
};

export type Costume = {
	id: string,
	project_id: string,
	character_id: string,
	name: string,
	description: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type CreateApiAccountInput = CreateApiAccountInput_Serialize | CreateApiAccountInput_Deserialize;

export type CreateApiAccountInput_Deserialize = {
	provider_id: string,
	label: string,
	/**
	 *  Plaintext API key. Written to the system keyring immediately and never
	 *  persisted to SQLite or returned to the caller.
	 */
	api_key: string,
	/**
	 *  Required for providers that need to push local assets to a public URL
	 *  (MS2: only `bailian`); ignored for others. Validation lives in
	 *  `account::service::validate_oss`.
	 */
	oss?: OssConfigInput | null,
};

export type CreateApiAccountInput_Serialize = {
	provider_id: string,
	label: string,
	/**
	 *  Plaintext API key. Written to the system keyring immediately and never
	 *  persisted to SQLite or returned to the caller.
	 */
	api_key: string,
	/**
	 *  Required for providers that need to push local assets to a public URL
	 *  (MS2: only `bailian`); ignored for others. Validation lives in
	 *  `account::service::validate_oss`.
	 */
	oss?: OssConfigInput | null,
};

export type CreateCharacterInput = {
	project_id: string,
	name: string,
	description?: string | null,
	appearance_prompt?: string | null,
	reference_image_path?: string | null,
};

export type CreateCheckpointInput = {
	episode_id: string,
	label: string | null,
	trigger_type?: string | null,
};

export type CreateCostumeInput = {
	project_id: string,
	/**
	 *  Required and must belong to the same `project_id`. Enforced at the
	 *  query layer; cross-project association is rejected with Validation.
	 */
	character_id: string,
	name: string,
	description?: string | null,
	reference_image_path?: string | null,
};

export type CreateEpisodeInput = {
	project_id: string,
	title: string,
	script_text?: string | null,
};

export type CreateGenerationTaskInput = {
	project_id?: string | null,
	shot_id?: string | null,
	provider_id: string,
	model_id: string,
	account_id: string,
	task_type: TaskKind,
	/**
	 *  JSON-encoded provider-specific parameters. Validated by the chosen
	 *  provider, not this layer; core only asserts it parses as JSON.
	 */
	params_json?: string | null,
};

export type CreateProjectInput = {
	name: string,
	/**
	 *  User-chosen subdirectory name under `<workspace>/projects/`. None
	 *  falls back to a slug derived from `name`. Must be a single path
	 *  segment — no separators, no `..`, no control chars.
	 */
	subdir?: string | null,
	description?: string | null,
	style_prompt?: string | null,
	global_seed?: number | null,
};

export type CreatePropInput = {
	project_id: string,
	name: string,
	description?: string | null,
	reference_image_path?: string | null,
};

export type CreateSceneInput = {
	project_id: string,
	name: string,
	description?: string | null,
	environment_prompt?: string | null,
	reference_image_path?: string | null,
};

export type CreateShotInput = {
	episode_id: string,
	summary?: string | null,
};

export type CreateVideoClipInput = {
	project_id: string,
	episode_id: string | null,
	source_asset_id: string,
	label: string | null,
	trim_start_ms: number | null,
	trim_end_ms: number | null,
};

export type Episode = {
	id: string,
	project_id: string,
	title: string,
	order_index: number,
	script_text: string,
	created_at: string,
	updated_at: string,
};

export type EpisodeCheckpoint = {
	id: string,
	episode_id: string,
	version_number: number,
	label: string | null,
	trigger_type: string,
	script_text: string,
	shots_json: string,
	canvas_nodes_json: string,
	canvas_edges_json: string,
	canvas_viewport_json: string,
	change_summary: string | null,
	created_at: string,
};

export type EpisodeCheckpointListItem = {
	id: string,
	episode_id: string,
	version_number: number,
	trigger_type: string,
	label: string | null,
	change_summary: string | null,
	created_at: string,
};

/**
 *  Emitted after a checkpoint restore completes. The frontend invalidates all
 *  episode-scoped queries (shots, canvas, script) on this event.
 */
export type EpisodeDataRestored = {
	episode_id: string,
};

export type EventPhase = "submit_upload" | "submit_call" | "poll" | "download" | "persist" | "cleanup";

export type EventSeverity = "info" | "warn" | "error";

/**  Real-time FFmpeg operation progress. Emitted while trim/split/concat runs. */
export type FfmpegProgressTick = {
	progress_pct: number | null,
	current_time_ms: number,
	total_duration_ms: number,
	speed: number | null,
};

export type FfmpegStatus = {
	available: boolean,
	version: string | null,
	path: string | null,
};

export type GenerationTask = {
	id: string,
	project_id: string | null,
	shot_id: string | null,
	provider_id: string,
	model_id: string,
	account_id: string,
	task_type: TaskKind,
	params_json: string,
	status: GenerationTaskStatus,
	result_asset_id: string | null,
	external_task_id: string | null,
	started_at: string | null,
	finished_at: string | null,
	error_message: string | null,
	retry_count: number,
	created_at: string,
	/**
	 *  Groups multiple tasks created from a single batch submission. NULL for
	 *  single-task submits (the MS2 path). Set by [`task_engine::submit_batch`]
	 *  to a UUID v4 shared by every row in the batch.
	 */
	batch_id: string | null,
};

export type GenerationTaskEvent = {
	id: number,
	task_id: string,
	occurred_at: string,
	phase: EventPhase,
	severity: EventSeverity,
	request_id: string | null,
	http_status: number | null,
	details_json: string,
	message: string,
};

export type GenerationTaskStatus = "pending" | "running" | "success" | "failed" | "cancelled";

export type ImportAssetInput = {
	project_id: string,
	/**  Absolute path of the external source file (drag-drop or file picker). */
	source_path: string,
	/**
	 *  Optional shot binding; MS1 reference-image flows leave this unset.
	 *  Empty strings are normalised to None.
	 */
	shot_id?: string | null,
	/**
	 *  Defaults to `Imported`. Callers running the AI generation pipeline
	 *  override this to `Generated` so library filters can split the two.
	 */
	source?: AssetSource,
};

/**
 *  IPC error payload — must implement `Serialize` to cross the IPC boundary,
 *  and `Type` so tauri-specta emits a matching TypeScript definition.
 * 
 *  `request_id` / `http_status` / `kind` are populated when the underlying
 *  failure originated from a structured `ProviderErrorDetail` (provider call
 *  or OSS upload), so the diagnostics UI can surface "复制 request_id" /
 *  HTTP code without a second IPC round-trip.
 */
export type IpcError = IpcError_Serialize | IpcError_Deserialize;

/**
 *  IPC error payload — must implement `Serialize` to cross the IPC boundary,
 *  and `Type` so tauri-specta emits a matching TypeScript definition.
 * 
 *  `request_id` / `http_status` / `kind` are populated when the underlying
 *  failure originated from a structured `ProviderErrorDetail` (provider call
 *  or OSS upload), so the diagnostics UI can surface "复制 request_id" /
 *  HTTP code without a second IPC round-trip.
 */
export type IpcError_Deserialize = {
	message: string,
	code: string,
	request_id: string | null,
	http_status: number | null,
	kind: ProviderErrorKind | null,
};

/**
 *  IPC error payload — must implement `Serialize` to cross the IPC boundary,
 *  and `Type` so tauri-specta emits a matching TypeScript definition.
 * 
 *  `request_id` / `http_status` / `kind` are populated when the underlying
 *  failure originated from a structured `ProviderErrorDetail` (provider call
 *  or OSS upload), so the diagnostics UI can surface "复制 request_id" /
 *  HTTP code without a second IPC round-trip.
 */
export type IpcError_Serialize = {
	message: string,
	code: string,
	request_id?: string | null,
	http_status?: number | null,
	kind?: ProviderErrorKind | null,
};

export type ListAssetsOptions = {
	project_id: string,
	asset_type?: AssetType | null,
	/**  Optional provenance filter (imported / generated). `None` means "any". */
	source?: AssetSource | null,
	/**
	 *  Optional case-insensitive substring match against `original_name`
	 *  or `label`. Empty / whitespace-only strings are treated as `None`.
	 */
	keyword?: string | null,
	/**
	 *  Optional exact-match filter on the `label` column. `Some("")` selects
	 *  rows with no label set (the canonical "unlabeled" state); `Some("x")`
	 *  selects rows whose label equals `"x"` exactly; `None` means "any".
	 */
	label?: string | null,
	limit?: number | null,
	offset?: number | null,
};

export type ListCharactersOptions = {
	project_id: string,
	limit?: number | null,
	offset?: number | null,
};

export type ListCostumesOptions = {
	project_id: string,
	character_id?: string | null,
	limit?: number | null,
	offset?: number | null,
};

export type ListEpisodesOptions = {
	project_id: string,
};

export type ListProjectsOptions = {
	limit?: number | null,
	offset?: number | null,
};

export type ListPropsOptions = {
	project_id: string,
	limit?: number | null,
	offset?: number | null,
};

export type ListScenesOptions = {
	project_id: string,
	limit?: number | null,
	offset?: number | null,
};

export type ListShotsOptions = {
	episode_id: string,
};

export type Model = {
	id: string,
	provider_id: string,
	name: string,
	/**
	 *  One of: 'text' | 'image' | 'video' | 'audio'. Enforced by a CHECK
	 *  constraint in `001_initial.sql`.
	 */
	model_type: string,
	/**  JSON metadata for model capability filtering. */
	capabilities_json: string | null,
	/**  JSON defaults used to prefill provider params. */
	default_params_json: string | null,
};

export type OssConfigInput = {
	endpoint: string,
	bucket: string,
	access_key_id: string,
	/**
	 *  Plaintext OSS secret. Persisted to the keyring immediately and dropped
	 *  from memory; never written to SQLite.
	 */
	access_key_secret: string,
	region?: string | null,
	url_expires_seconds?: number,
};

/**
 *  OSS configuration as exposed back to the frontend / IPC. Mirrors
 *  `OssConfigInput` minus `access_key_secret`.
 */
export type OssConfigPublic = OssConfigPublic_Serialize | OssConfigPublic_Deserialize;

/**
 *  OSS configuration as exposed back to the frontend / IPC. Mirrors
 *  `OssConfigInput` minus `access_key_secret`.
 */
export type OssConfigPublic_Deserialize = {
	endpoint: string,
	bucket: string,
	/**
	 *  AccessKey ID is fine to surface — it's the public half of the credential
	 *  pair. Pairs with the secret stored in keyring.
	 */
	access_key_id: string,
	region?: string | null,
	/**
	 *  Validity (seconds) for presigned GET URLs minted by this account's
	 *  uploader. Defaults to 3600.
	 */
	url_expires_seconds: number,
};

/**
 *  OSS configuration as exposed back to the frontend / IPC. Mirrors
 *  `OssConfigInput` minus `access_key_secret`.
 */
export type OssConfigPublic_Serialize = {
	endpoint: string,
	bucket: string,
	/**
	 *  AccessKey ID is fine to surface — it's the public half of the credential
	 *  pair. Pairs with the secret stored in keyring.
	 */
	access_key_id: string,
	region?: string | null,
	/**
	 *  Validity (seconds) for presigned GET URLs minted by this account's
	 *  uploader. Defaults to 3600.
	 */
	url_expires_seconds: number,
};

export type Project = {
	id: string,
	name: string,
	description: string,
	style_prompt: string,
	/**
	 *  Workspace-relative POSIX path to the project root (e.g.
	 *  `projects/ep4-the-rain`). Resolved to an absolute filesystem path at
	 *  the IPC boundary by `paths::resolve_project_root(workspace, ...)`, so
	 *  frontend consumers see an absolute path. The relative form keeps the
	 *  whole workspace portable across machines.
	 */
	root_path: string,
	global_seed: number | null,
	created_at: string,
	updated_at: string,
};

export type Prop = {
	id: string,
	project_id: string,
	name: string,
	description: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type Provider = {
	id: string,
	name: string,
	base_url: string,
	auth_type: string,
	docs_url: string,
};

export type ProviderErrorKind = 
/**  401 / 403 — invalid or expired API key, missing scope. */
"auth" | 
/**  429 — over rate limit; retryable with backoff. */
"rate_limited" | 
/**  403 with quota/balance signal — non-retryable until topped up. */
"quota" | 
/**  4xx — schema or business validation failure. */
"invalid_request" | 
/**  Connection refused, DNS, TLS — typically transient. */
"network" | 
/**  Client-side timeout. */
"timeout" | 
/**  2xx with body that does not deserialize. */
"malformed" | 
/**  5xx or anything we did not classify. */
"unknown";

export type Scene = {
	id: string,
	project_id: string,
	name: string,
	description: string,
	environment_prompt: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type Shot = {
	id: string,
	episode_id: string,
	order_index: number,
	summary: string,
	duration_sec: number | null,
	camera_angle: string,
	shot_type: string,
	mood: string,
	dialogue: string,
	video_prompt: string,
	image_prompt: string,
	status: ShotStatus,
	adopted_asset_id: string | null,
	created_at: string,
	updated_at: string,
};

export type ShotLinks = {
	character_ids: string[],
	scene_ids: string[],
	prop_ids: string[],
};

export type ShotStatus = "draft" | "ready" | "generating" | "done";

/**
 *  Which side-table a subject points to. Used by `link_shot_subject` /
 *  `unlink_shot_subject` to dispatch to the right join table without
 *  exploding the IPC surface into three near-identical commands.
 */
export type SubjectKind = "character" | "scene" | "prop";

export type SubmitBatchOutcome = {
	/**
	 *  UUID v4 shared by every task row created by this submission. Echoes
	 *  the `generation_task.batch_id` column for downstream filtering.
	 */
	batch_id: string,
	/**  Task IDs in the caller-supplied input order. */
	task_ids: string[],
	created_count: number,
};

/**
 *  A new diagnostic event has been persisted for `task_id`. Carries the full
 *  row so the front-end can append to the cached timeline without an extra
 *  `list_task_events` round-trip.
 */
export type TaskEventLogged = {
	task_id: string,
	event: GenerationTaskEvent,
};

export type TaskKind = "text" | "image" | "video" | "audio";

/**
 *  Numeric progress hint emitted in real time during `Running`. Not persisted —
 *  purely a UI heartbeat. The front-end should display this only while the
 *  task is in `Running`; cleared on terminal status.
 */
export type TaskProgressTick = {
	task_id: string,
	progress: number,
};

export type TaskStatusChanged = {
	task_id: string,
	status: GenerationTaskStatus,
	/**  0..=100; `None` means the provider does not report progress. */
	progress: number | null,
	error_message: string | null,
};

export type ThumbnailStripResult = {
	thumbnails: string[],
	interval_ms: number,
	count: number,
};

export type TrimMode = "Copy" | "Reencode";

export type UpdateApiAccountInput = UpdateApiAccountInput_Serialize | UpdateApiAccountInput_Deserialize;

export type UpdateApiAccountInput_Deserialize = {
	label?: string | null,
	/**  Some(new_key) replaces the keyring entry; None leaves it untouched. */
	api_key?: string | null,
	/**
	 *  Some(_) replaces the entire OSS config (all 4+ fields together); None
	 *  leaves it untouched. Sub-field updates are intentionally not supported
	 *  — the frontend always re-submits the whole block.
	 */
	oss?: OssConfigInput | null,
};

export type UpdateApiAccountInput_Serialize = {
	label?: string | null,
	/**  Some(new_key) replaces the keyring entry; None leaves it untouched. */
	api_key?: string | null,
	/**
	 *  Some(_) replaces the entire OSS config (all 4+ fields together); None
	 *  leaves it untouched. Sub-field updates are intentionally not supported
	 *  — the frontend always re-submits the whole block.
	 */
	oss?: OssConfigInput | null,
};

export type UpdateCharacterInput = UpdateCharacterInput_Serialize | UpdateCharacterInput_Deserialize;

export type UpdateCharacterInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	appearance_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateCharacterInput_Serialize = {
	name?: string | null,
	description?: string | null,
	appearance_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateCostumeInput = UpdateCostumeInput_Serialize | UpdateCostumeInput_Deserialize;

export type UpdateCostumeInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateCostumeInput_Serialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateEpisodeInput = UpdateEpisodeInput_Serialize | UpdateEpisodeInput_Deserialize;

export type UpdateEpisodeInput_Deserialize = {
	title?: string | null,
	script_text?: string | null,
};

export type UpdateEpisodeInput_Serialize = {
	title?: string | null,
	script_text?: string | null,
};

export type UpdateProjectInput = UpdateProjectInput_Serialize | UpdateProjectInput_Deserialize;

export type UpdateProjectInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	style_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	global_seed?: number | null,
};

export type UpdateProjectInput_Serialize = {
	name?: string | null,
	description?: string | null,
	style_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	global_seed?: number | null,
};

export type UpdatePropInput = UpdatePropInput_Serialize | UpdatePropInput_Deserialize;

export type UpdatePropInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdatePropInput_Serialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateSceneInput = UpdateSceneInput_Serialize | UpdateSceneInput_Deserialize;

export type UpdateSceneInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	environment_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateSceneInput_Serialize = {
	name?: string | null,
	description?: string | null,
	environment_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateShotInput = UpdateShotInput_Serialize | UpdateShotInput_Deserialize;

export type UpdateShotInput_Deserialize = {
	summary?: string | null,
	/**  None = don't modify, Some(None) = clear, Some(Some(v)) = set */
	duration_sec?: number | null,
	camera_angle?: string | null,
	shot_type?: string | null,
	mood?: string | null,
	dialogue?: string | null,
	video_prompt?: string | null,
	image_prompt?: string | null,
	status?: ShotStatus | null,
};

export type UpdateShotInput_Serialize = {
	summary?: string | null,
	/**  None = don't modify, Some(None) = clear, Some(Some(v)) = set */
	duration_sec?: number | null,
	camera_angle?: string | null,
	shot_type?: string | null,
	mood?: string | null,
	dialogue?: string | null,
	video_prompt?: string | null,
	image_prompt?: string | null,
	status?: ShotStatus | null,
};

export type UpdateVideoClipInput = {
	label: string | null,
	trim_start_ms: number | null,
	trim_end_ms: number | null,
};

export type UpsertCanvasLayoutInput = {
	episode_id: string,
	nodes_json: string,
	edges_json: string,
	viewport_json: string,
};

export type VideoClip = {
	id: string,
	project_id: string,
	episode_id: string | null,
	source_asset_id: string,
	label: string | null,
	trim_start_ms: number | null,
	trim_end_ms: number | null,
	order_index: number,
	created_at: string,
};

export type VideoMetadata = {
	duration_ms: number,
	width: number,
	height: number,
	video_codec: string,
	audio_codec: string | null,
	fps: number | null,
	bitrate_kbps: number | null,
	file_size_bytes: number,
};

/**
 *  Classification of a candidate workspace directory. Each variant drives a
 *  different confirmation flow in the frontend onboarding / switch UI.
 */
export type WorkspaceProbe = 
/**  Path does not exist OR is an empty directory. Safe to initialise. */
{ kind: "empty" } | 
/**
 *  Path contains `mango.db`. Reports the number of projects found so the
 *  UI can show "detected N projects, mount here?". Project count is
 *  best-effort — a corrupt DB still classifies as ExistingMangoData
 *  with `project_count = 0` rather than failing.
 */
{ kind: "existing_mango_data"; project_count: number } | 
/**
 *  Path exists, is non-empty, but no `mango.db` was found. The UI should
 *  warn before initialising on top of unrelated files.
 */
{ kind: "non_empty_foreign" } | 
/**
 *  Path is unreadable, not a directory, or otherwise unusable. The string
 *  is a human-readable reason for the UI to surface.
 */
{ kind: "invalid"; reason: string };

/**  Snapshot of workspace mount state for the frontend router. */
export type WorkspaceStatus = {
	/**
	 *  Absolute path of the mounted workspace, or `None` if onboarding is
	 *  required.
	 */
	workspace_root: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

