// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Delete an asset row. Files on disk are intentionally not removed; a future
	 *  GC sweep (V2) reconciles orphaned files. See spec-12 §"错误场景".
	 */
	deleteAsset: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_asset", { id })),
	getAsset: (id: string) => typedError<Asset, IpcError>(__TAURI_INVOKE("get_asset", { id })),
	/**
	 *  Import an external image into the project.
	 * 
	 *  Runs in three stages so the file-IO stage (potentially tens of MiB of
	 *  copy + image decode) does NOT hold the tokio-rusqlite worker. Stages 1
	 *  and 3 are short DB-bound calls; stage 2 is `spawn_blocking` filesystem
	 *  work. See spec-12 §"导入流水线（三段式）" for the design rationale.
	 */
	importAsset: (input: ImportAssetInput) => typedError<Asset, IpcError>(__TAURI_INVOKE("import_asset", { input })),
	listAssets: (opts: ListAssetsOptions) => typedError<Asset[], IpcError>(__TAURI_INVOKE("list_assets", { opts })),
	/**
	 *  Allow the asset protocol to read files under `project_root`. The webview
	 *  needs this before `convertFileSrc(<absolute path>)` URLs can resolve.
	 *  Safe to call repeatedly; `allow_directory` is idempotent.
	 */
	registerProjectAssetScope: (projectId: string) => typedError<null, IpcError>(__TAURI_INVOKE("register_project_asset_scope", { projectId })),
	createCharacter: (input: CreateCharacterInput) => typedError<Character, IpcError>(__TAURI_INVOKE("create_character", { input })),
	/**
	 *  Delete a character. Schema `ON DELETE CASCADE` removes its costumes;
	 *  callers display the affected count by querying costumes first.
	 */
	deleteCharacter: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_character", { id })),
	getCharacter: (id: string) => typedError<Character, IpcError>(__TAURI_INVOKE("get_character", { id })),
	listCharacters: (opts: ListCharactersOptions) => typedError<Character[], IpcError>(__TAURI_INVOKE("list_characters", { opts })),
	updateCharacter: (id: string, input: UpdateCharacterInput_Deserialize) => typedError<Character, IpcError>(__TAURI_INVOKE("update_character", { id, input })),
	createCostume: (input: CreateCostumeInput) => typedError<Costume, IpcError>(__TAURI_INVOKE("create_costume", { input })),
	deleteCostume: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_costume", { id })),
	getCostume: (id: string) => typedError<Costume, IpcError>(__TAURI_INVOKE("get_costume", { id })),
	listCostumes: (opts: ListCostumesOptions) => typedError<Costume[], IpcError>(__TAURI_INVOKE("list_costumes", { opts })),
	updateCostume: (id: string, input: UpdateCostumeInput_Deserialize) => typedError<Costume, IpcError>(__TAURI_INVOKE("update_costume", { id, input })),
	/**
	 *  Open a native directory picker. Returns `None` if the user cancelled.
	 * 
	 *  Implemented with the non-blocking callback variant + a oneshot channel so
	 *  the tokio executor thread is not parked while the user is choosing.
	 */
	pickProjectDirectory: () => typedError<string | null, IpcError>(__TAURI_INVOKE("pick_project_directory")),
	/**
	 *  Suggest a default project root for a given (display) name. The returned
	 *  path is `<app_data>/projects/<slug>` where slug is name-derived for human
	 *  readability; the actual persisted root is whatever the user submits.
	 */
	suggestProjectRoot: (projectName: string) => typedError<string, IpcError>(__TAURI_INVOKE("suggest_project_root", { projectName })),
	createProject: (input: CreateProjectInput) => typedError<Project, IpcError>(__TAURI_INVOKE("create_project", { input })),
	/**
	 *  Delete project metadata only. The on-disk root_path directory and its
	 *  contents are intentionally preserved; V2 will add an explicit purge flag.
	 */
	deleteProject: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_project", { id })),
	getProject: (id: string) => typedError<Project, IpcError>(__TAURI_INVOKE("get_project", { id })),
	listProjects: (opts: {
	limit?: number | null,
	offset?: number | null,
} | null) => typedError<Project[], IpcError>(__TAURI_INVOKE("list_projects", { opts })),
	updateProject: (id: string, input: UpdateProjectInput_Deserialize) => typedError<Project, IpcError>(__TAURI_INVOKE("update_project", { id, input })),
	createProp: (input: CreatePropInput) => typedError<Prop, IpcError>(__TAURI_INVOKE("create_prop", { input })),
	deleteProp: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_prop", { id })),
	getProp: (id: string) => typedError<Prop, IpcError>(__TAURI_INVOKE("get_prop", { id })),
	listProps: (opts: ListPropsOptions) => typedError<Prop[], IpcError>(__TAURI_INVOKE("list_props", { opts })),
	updateProp: (id: string, input: UpdatePropInput_Deserialize) => typedError<Prop, IpcError>(__TAURI_INVOKE("update_prop", { id, input })),
	createScene: (input: CreateSceneInput) => typedError<Scene, IpcError>(__TAURI_INVOKE("create_scene", { input })),
	deleteScene: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_scene", { id })),
	getScene: (id: string) => typedError<Scene, IpcError>(__TAURI_INVOKE("get_scene", { id })),
	listScenes: (opts: ListScenesOptions) => typedError<Scene[], IpcError>(__TAURI_INVOKE("list_scenes", { opts })),
	updateScene: (id: string, input: UpdateSceneInput_Deserialize) => typedError<Scene, IpcError>(__TAURI_INVOKE("update_scene", { id, input })),
};

/* Types */
export type Asset = {
	id: string,
	project_id: string,
	shot_id: string | null,
	asset_type: AssetType,
	original_name: string,
	/**
	 *  Stored relative to the project root (e.g. `assets/{id}.png`), always
	 *  `/`-separated for cross-platform stability.
	 */
	file_path: string,
	thumbnail_path: string | null,
	file_size: number,
	content_hash: string | null,
	metadata_json: string | null,
	created_at: string,
	updated_at: string,
};

export type AssetType = "image" | "video" | "audio" | "script";

export type Character = {
	id: string,
	project_id: string,
	name: string,
	description: string,
	appearance_prompt: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type Costume = {
	id: string,
	project_id: string,
	character_id: string,
	name: string,
	description: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type CreateCharacterInput = {
	project_id: string,
	name: string,
	description?: string | null,
	appearance_prompt?: string | null,
	reference_image_path?: string | null,
};

export type CreateCostumeInput = {
	project_id: string,
	/**
	 *  Required and must belong to the same `project_id`. Enforced at the
	 *  query layer; cross-project association is rejected with Validation.
	 */
	character_id: string,
	name: string,
	description?: string | null,
	reference_image_path?: string | null,
};

export type CreateProjectInput = {
	name: string,
	/**
	 *  None → fall back to `<app_data>/projects/{uuid}/` (convention path).
	 *  Some(path) → must be absolute and empty/non-existent (validated).
	 */
	root_path?: string | null,
	description?: string | null,
	style_prompt?: string | null,
	global_seed?: number | null,
};

export type CreatePropInput = {
	project_id: string,
	name: string,
	description?: string | null,
	reference_image_path?: string | null,
};

export type CreateSceneInput = {
	project_id: string,
	name: string,
	description?: string | null,
	environment_prompt?: string | null,
	reference_image_path?: string | null,
};

export type ImportAssetInput = {
	project_id: string,
	/**  Absolute path of the external source file (drag-drop or file picker). */
	source_path: string,
	/**
	 *  Optional shot binding; MS1 reference-image flows leave this unset.
	 *  Empty strings are normalised to None.
	 */
	shot_id?: string | null,
};

/**
 *  IPC error payload — must implement `Serialize` to cross the IPC boundary,
 *  and `Type` so tauri-specta emits a matching TypeScript definition.
 */
export type IpcError = {
	message: string,
	code: string,
};

export type ListAssetsOptions = {
	project_id: string,
	asset_type?: AssetType | null,
	limit?: number | null,
	offset?: number | null,
};

export type ListCharactersOptions = {
	project_id: string,
	limit?: number | null,
	offset?: number | null,
};

export type ListCostumesOptions = {
	project_id: string,
	character_id?: string | null,
	limit?: number | null,
	offset?: number | null,
};

export type ListProjectsOptions = {
	limit?: number | null,
	offset?: number | null,
};

export type ListPropsOptions = {
	project_id: string,
	limit?: number | null,
	offset?: number | null,
};

export type ListScenesOptions = {
	project_id: string,
	limit?: number | null,
	offset?: number | null,
};

export type Project = {
	id: string,
	name: string,
	description: string,
	style_prompt: string,
	/**
	 *  Absolute filesystem path to the project root directory. Guaranteed
	 *  non-empty by `startup::backfill_project_roots` for legacy rows and by
	 *  `queries::project::create` for all new rows.
	 */
	root_path: string,
	global_seed: number | null,
	created_at: string,
	updated_at: string,
};

export type Prop = {
	id: string,
	project_id: string,
	name: string,
	description: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type Scene = {
	id: string,
	project_id: string,
	name: string,
	description: string,
	environment_prompt: string,
	reference_image_path: string | null,
	created_at: string,
	updated_at: string,
};

export type UpdateCharacterInput = UpdateCharacterInput_Serialize | UpdateCharacterInput_Deserialize;

export type UpdateCharacterInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	appearance_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateCharacterInput_Serialize = {
	name?: string | null,
	description?: string | null,
	appearance_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateCostumeInput = UpdateCostumeInput_Serialize | UpdateCostumeInput_Deserialize;

export type UpdateCostumeInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateCostumeInput_Serialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateProjectInput = UpdateProjectInput_Serialize | UpdateProjectInput_Deserialize;

export type UpdateProjectInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	style_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	global_seed?: number | null,
};

export type UpdateProjectInput_Serialize = {
	name?: string | null,
	description?: string | null,
	style_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	global_seed?: number | null,
};

export type UpdatePropInput = UpdatePropInput_Serialize | UpdatePropInput_Deserialize;

export type UpdatePropInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdatePropInput_Serialize = {
	name?: string | null,
	description?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateSceneInput = UpdateSceneInput_Serialize | UpdateSceneInput_Deserialize;

export type UpdateSceneInput_Deserialize = {
	name?: string | null,
	description?: string | null,
	environment_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

export type UpdateSceneInput_Serialize = {
	name?: string | null,
	description?: string | null,
	environment_prompt?: string | null,
	/**  None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v */
	reference_image_path?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

