// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackType } from "./TrackType";

export type CreateTimelineTrackInput = { episode_id: string, track_type: TrackType, label: string, };
