// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProjectInput = { name: string, description: string | null, style_prompt: string | null, global_seed: number | null, };
