// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemType } from "./ItemType";

export type CreateTimelineItemInput = { track_id: string, asset_id: string | null, item_type: ItemType, position_ms: number, duration_ms: number, in_point_ms: number | null, out_point_ms: number, params_json: string | null, };
