// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, name: string, description: string, style_prompt: string, global_seed: number | null, created_at: string, updated_at: string, };
