// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioRole } from "./AudioRole";

export type ShotAudio = { id: string, shot_id: string, asset_id: string, audio_role: AudioRole, volume: number, offset_ms: number, order_index: number, created_at: string, };
