// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackType } from "./TrackType";

export type TimelineTrack = { id: string, episode_id: string, track_type: TrackType, label: string, order_index: number, muted: boolean, locked: boolean, created_at: string, };
