// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineKeyframe = { id: string, item_id: string, property: string, time_ms: number, value: number, easing: string, created_at: string, };
