// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProjectInput = { name?: string | null, description?: string | null, style_prompt?: string | null, 
/**
 * None = don't modify, Some(None) = clear to NULL, Some(Some(v)) = set to v
 */
global_seed?: number | null | null, };
