// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTimelineItemInput = { position_ms: number | null, duration_ms: number | null, in_point_ms: number | null, out_point_ms: number | null, params_json: string | null, };
