// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoClip = { id: string, project_id: string, episode_id: string | null, source_asset_id: string, label: string | null, trim_start_ms: number | null, trim_end_ms: number | null, order_index: number, created_at: string, };
