// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoMetadata = { duration_ms: number, width: number, height: number, video_codec: string, audio_codec: string | null, fps: number, bitrate_kbps: number | null, file_size_bytes: number, };
